// DriverLang.js — Driver app translations (English + Spanish only)
// Used by DriverApp to translate all UI strings

export const DRIVER_LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
]

export const DRIVER_T = {
  en: {"home": "Home", "earnings": "Earnings", "orders": "Orders", "profile": "Profile", "online": "Online", "offline": "Offline", "goOnline": "Go online", "goOffline": "Go offline", "newOrder": "New order", "accept": "Accept", "reject": "Reject", "pickUp": "Pick up", "deliver": "Deliver", "delivered": "Delivered", "navigateTo": "Navigate to", "customer": "Customer", "address": "Address", "items": "Items", "total": "Total", "orderReady": "Order ready for collection", "onMyWay": "On my way", "arrivedAtDepot": "Arrived at depot", "arrivedAtCustomer": "Arrived at customer", "markDelivered": "Mark as delivered", "issueWithOrder": "Issue with order", "contactCustomer": "Contact customer", "contactDepot": "Contact depot", "todayEarnings": "Today's earnings", "weekEarnings": "This week", "totalDeliveries": "Deliveries", "rating": "Rating", "myProfile": "My profile", "signOut": "Sign out", "loading": "Loading...", "noOrders": "No orders available", "waitingForOrders": "Waiting for orders...", "etaMinutes": "ETA", "distance": "Distance", "tip": "Tip", "goodMorning": "Good morning", "goodAfternoon": "Good afternoon", "goodEvening": "Good evening", "language": "Language", "english": "English", "spanish": "Spanish", "settings": "Settings", "help": "Help", "emergency": "Emergency", "takingABreak": "Taking a break", "back": "Back", "cancel": "Cancel", "confirm": "Confirm", "orderNumber": "Order", "notes": "Notes", "noNotes": "No special notes", "specialInstructions": "Special instructions", "leaveAtDoor": "Leave at door", "ageVerification": "Age verification required", "checkId": "Check customer ID", "photoProof": "Take photo proof", "scanCode": "Scan delivery code", "bonus": "Bonus", "topDriver": "Top driver", "yourShift": "Your shift"},
  es: {"home": "Inicio", "earnings": "Ganancias", "orders": "Pedidos", "profile": "Perfil", "online": "En línea", "offline": "Desconectado", "goOnline": "Conectarse", "goOffline": "Desconectarse", "newOrder": "Nuevo pedido", "accept": "Aceptar", "reject": "Rechazar", "pickUp": "Recoger", "deliver": "Entregar", "delivered": "Entregado", "navigateTo": "Navegar a", "customer": "Cliente", "address": "Dirección", "items": "Artículos", "total": "Total", "orderReady": "Pedido listo para recoger", "onMyWay": "En camino", "arrivedAtDepot": "Llegué al depósito", "arrivedAtCustomer": "Llegué al cliente", "markDelivered": "Marcar como entregado", "issueWithOrder": "Problema con el pedido", "contactCustomer": "Contactar cliente", "contactDepot": "Contactar depósito", "todayEarnings": "Ganancias de hoy", "weekEarnings": "Esta semana", "totalDeliveries": "Entregas", "rating": "Valoración", "myProfile": "Mi perfil", "signOut": "Cerrar sesión", "loading": "Cargando...", "noOrders": "Sin pedidos disponibles", "waitingForOrders": "Esperando pedidos...", "etaMinutes": "ETA", "distance": "Distancia", "tip": "Propina", "goodMorning": "Buenos días", "goodAfternoon": "Buenas tardes", "goodEvening": "Buenas noches", "language": "Idioma", "english": "Inglés", "spanish": "Español", "settings": "Ajustes", "help": "Ayuda", "emergency": "Emergencia", "takingABreak": "Tomando un descanso", "back": "Atrás", "cancel": "Cancelar", "confirm": "Confirmar", "orderNumber": "Pedido", "notes": "Notas", "noNotes": "Sin notas especiales", "specialInstructions": "Instrucciones especiales", "leaveAtDoor": "Dejar en la puerta", "ageVerification": "Verificación de edad requerida", "checkId": "Verificar ID del cliente", "photoProof": "Tomar foto de entrega", "scanCode": "Escanear código de entrega", "bonus": "Bonificación", "topDriver": "Mejor repartidor", "yourShift": "Tu turno"},
}

export function useDriverT(lang) {
  return DRIVER_T[lang] || DRIVER_T.en
}
